export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const GET_DETAILS = 'GET_DETAILS'
export const CLEAR_DETAILS = 'CLEAR_DETAILS'
export const GET_GENRES = 'GET_GENRES'
export const GET_GAME_BY_NAME = 'GET_GAME_BY_NAME'
export const POST_VIDEOGAME = 'POST_VIDEOGAME'
export const POST_VIDEOGAME_SUCCESS = 'POST_VIDEOGAME_SUCCESS';
export const POST_VIDEOGAME_FAILURE = 'POST_VIDEOGAME_FAILURE'
export const ORDER_ASC_DESC = 'ORDER_ASC_DESC'
export const ORDER_BY_RATING = 'ORDER_BY_RATING'
export const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN'
export const FILTER_BY_GENRE = 'FILTER_BY_GENRE'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE';

